<a href="https://colab.research.google.com/github/sngillard/student-outcome-classification/blob/main/notebooks/01_data_preprocessing_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load raw data from CSV via GitHub link
df = pd.read_csv('https://raw.githubusercontent.com/sngillard/student-outcome-classification/refs/heads/main/data/raw/student_data_raw.csv'
)

# Fix spelling error in column
df.rename(columns={"Nacionality" : "Nationality"}, inplace=True)

# View first 20 rows
df.head(20)

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Nationality,Mother's qualification,Father's qualification,Mother's occupation,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,8,5,2,1,1,1,13,10,6,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,6,1,11,1,1,1,1,3,4,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,5,1,1,1,22,27,10,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,8,2,15,1,1,1,23,27,6,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,12,1,3,0,1,1,22,28,10,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
5,2,12,1,17,0,12,1,22,27,10,...,0,5,17,5,11.500000,5,16.2,0.3,-0.92,Graduate
6,1,1,1,12,1,1,1,13,28,8,...,0,8,8,8,14.345000,0,15.5,2.8,-4.06,Graduate
7,1,9,4,11,1,1,1,22,27,10,...,0,5,5,0,0.000000,0,15.5,2.8,-4.06,Dropout
8,1,1,3,10,1,1,15,1,1,10,...,0,6,7,6,14.142857,0,16.2,0.3,-0.92,Graduate
9,1,1,1,10,1,1,1,1,14,5,...,0,6,14,2,13.500000,0,8.9,1.4,3.51,Dropout
10,1,1,1,14,1,1,1,23,14,6,...,0,6,7,5,14.200000,0,13.9,-0.3,0.79,Graduate
11,1,1,1,12,1,1,1,13,28,10,...,0,8,8,7,13.214286,0,12.7,3.7,-1.70,Graduate
12,1,1,2,16,1,1,1,13,27,5,...,0,6,0,0,0.000000,0,12.7,3.7,-1.70,Dropout
13,1,17,1,11,1,16,1,1,1,5,...,0,6,8,5,11.000000,0,8.9,1.4,3.51,Graduate
14,1,1,1,6,1,1,1,23,27,6,...,0,5,5,5,12.000000,0,10.8,1.4,1.74,Graduate
15,1,1,1,15,1,1,1,13,27,10,...,0,6,7,0,0.000000,0,15.5,2.8,-4.06,Dropout
16,1,9,1,10,1,1,1,13,28,6,...,0,6,14,2,11.000000,0,10.8,1.4,1.74,Enrolled
17,1,8,2,12,1,1,1,13,1,6,...,0,8,8,8,14.545000,0,15.5,2.8,-4.06,Graduate
18,1,1,1,8,1,1,1,3,14,4,...,0,5,8,4,12.250000,2,10.8,1.4,1.74,Graduate
19,1,1,1,16,1,1,1,13,14,8,...,0,7,8,6,13.500000,0,16.2,0.3,-0.92,Enrolled

In [3]:
# Check for missing values
df.info()

# None missing (4424 entries, indexes 0-4423

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 35 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance                      4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Nationality                                     4424 non-null   int64
 7   Mother's qualification                          4424 non-null   int64
 8   Father's qualification                          4424 non-null   int64
 9   Mother's occupation                             4424 non-null   int64
 10  Father's occupation                             4424 non-null   int64
 11  Displaced                                       4424 non-null   int64
 12  Educational special needs                       4424 non-null   int64
 13  Debtor                                          4424 non-null   int64
 14  Tuition fees up to date                         4424 non-null   int64
 15  Gender                                          4424 non-null   int64
 16  Scholarship holder                              4424 non-null   int64
 17  Age at enrollment                               4424 non-null   int64
 18  International                                   4424 non-null   int64
 19  Curricular units 1st sem (credited)             4424 non-null   int64
 20  Curricular units 1st sem (enrolled)             4424 non-null   int64
 21  Curricular units 1st sem (evaluations)          4424 non-null   int64
 22  Curricular units 1st sem (approved)             4424 non-null   int64
 23  Curricular units 1st sem (grade)                4424 non-null   float64
 24  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 25  Curricular units 2nd sem (credited)             4424 non-null   int64
 26  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 27  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 28  Curricular units 2nd sem (approved)             4424 non-null   int64
 29  Curricular units 2nd sem (grade)                4424 non-null   float64
 30  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 31  Unemployment rate                               4424 non-null   float64
 32  Inflation rate                                  4424 non-null   float64
 33  GDP                                             4424 non-null   float64
 34  Target                                          4424 non-null   object
dtypes: float64(5), int64(29), object(1)
memory usage: 1.2+ MB

In [4]:
# Describe the stats of the df (no missing values)
df.describe(include="all").transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Marital status,4424.0,NaN,NaN,NaN,1.178571,0.605747,1.0,1.0,1.0,1.0,6.0
Application mode,4424.0,NaN,NaN,NaN,6.88698,5.298964,1.0,1.0,8.0,12.0,18.0
Application order,4424.0,NaN,NaN,NaN,1.727848,1.313793,0.0,1.0,1.0,2.0,9.0
Course,4424.0,NaN,NaN,NaN,9.899186,4.331792,1.0,6.0,10.0,13.0,17.0
Daytime/evening attendance,4424.0,NaN,NaN,NaN,0.890823,0.311897,0.0,1.0,1.0,1.0,1.0
Previous qualification,4424.0,NaN,NaN,NaN,2.53142,3.963707,1.0,1.0,1.0,1.0,17.0
Nationality,4424.0,NaN,NaN,NaN,1.254521,1.748447,1.0,1.0,1.0,1.0,21.0
Mother's qualification,4424.0,NaN,NaN,NaN,12.322107,9.026251,1.0,2.0,13.0,22.0,29.0
Father's qualification,4424.0,NaN,NaN,NaN,16.455244,11.0448,1.0,3.0,14.0,27.0,34.0
Mother's occupation,4424.0,NaN,NaN,NaN,7.317812,3.997828,1.0,5.0,6.0,10.0,32.0
Father's occupation,4424.0,NaN,NaN,NaN,7.819168,4.856692,1.0,5.0,8.0,10.0,46.0
Displaced,4424.0,NaN,NaN,NaN,0.548373,0.497711,0.0,0.0,1.0,1.0,1.0
Educational special needs,4424.0,NaN,NaN,NaN,0.011528,0.10676,0.0,0.0,0.0,0.0,1.0
Debtor,4424.0,NaN,NaN,NaN,0.113698,0.31748,0.0,0.0,0.0,0.0,1.0
Tuition fees up to date,4424.0,NaN,NaN,NaN,0.880651,0.324235,0.0,1.0,1.0,1.0,1.0
Gender,4424.0,NaN,NaN,NaN,0.351718,0.47756,0.0,0.0,0.0,1.0,1.0
Scholarship holder,4424.0,NaN,NaN,NaN,0.248418,0.432144,0.0,0.0,0.0,0.0,1.0
Age at enrollment,4424.0,NaN,NaN,NaN,23.265145,7.587816,17.0,19.0,20.0,25.0,70.0
International,4424.0,NaN,NaN,NaN,0.024864,0.155729,0.0,0.0,0.0,0.0,1.0
Curricular units 1st sem (credited),4424.0,NaN,NaN,NaN,0.709991,2.360507,0.0,0.0,0.0,0.0,20.0
Curricular units 1st sem (enrolled),4424.0,NaN,NaN,NaN,6.27057,2.480178,0.0,5.0,6.0,7.0,26.0
Curricular units 1st sem (evaluations),4424.0,NaN,NaN,NaN,8.299051,4.179106,0.0,6.0,8.0,10.0,45.0
Curricular units 1st sem (approved),4424.0,NaN,NaN,NaN,4.7066,3.094238,0.0,3.0,5.0,6.0,26.0
Curricular units 1st sem (grade),4424.0,NaN,NaN,NaN,10.640822,4.843663,0.0,11.0,12.285714,13.4,18.875
Curricular units 1st sem (without evaluations),4424.0,NaN,NaN,NaN,0.137658,0.69088,0.0,0.0,0.0,0.0,12.0
Curricular units 2nd sem (credited),4424.0,NaN,NaN,NaN,0.541817,1.918546,0.0,0.0,0.0,0.0,19.0
Curricular units 2nd sem (enrolled),4424.0,NaN,NaN,NaN,6.232143,2.195951,0.0,5.0,6.0,7.0,23.0
Curricular units 2nd sem (evaluations),4424.0,NaN,NaN,NaN,8.063291,3.947951,0.0,6.0,8.0,10.0,33.0
Curricular units 2nd sem (approved),4424.0,NaN,NaN,NaN,4.435805,3.014764,0.0,2.0,5.0,6.0,20.0
Curricular units 2nd sem (grade),4424.0,NaN,NaN,NaN,10.230206,5.210808,0.0,10.75,12.2,13.333333,18.571429
Curricular units 2nd sem (without evaluations),4424.0,NaN,NaN,NaN,0.150316,0.753774,0.0,0.0,0.0,0.0,12.0
Unemployment rate,4424.0,NaN,NaN,NaN,11.566139,2.66385,7.6,9.4,11.1,13.9,16.2
Inflation rate,4424.0,NaN,NaN,NaN,1.228029,1.382711,-0.8,0.3,1.4,2.6,3.7
GDP,4424.0,NaN,NaN,NaN,0.001969,2.269935,-4.06,-1.7,0.32,1.79,3.51
Target,4424,3,Graduate,2209,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
le = LabelEncoder()
# Fit label encoder and return encoded labels
df["Target"] = le.fit_transform(df["Target"])
# Return count of unique values
df["Target"].value_counts()

Target
2    2209
0    1421
1     794
Name: count, dtype: int64

In [6]:
# Split into X (features) and y (target variable aka "Target" column which is drop out or 0, enrolled or 1, or graduate or 2)
X = df.drop(columns=['Target'], axis=1)
y = df['Target']

# Scale numeric features for logistic regression
std_scaler = StandardScaler()

# StandardScaler scales feature data and creates a NumPy array called X_features_scaled_array that contains the X/feature values
X_features_scaled_array = std_scaler.fit_transform(X)

# Turn scaled X_features_scaled_array into a Dataframe with original column names
X_scaled = pd.DataFrame(X_features_scaled_array, columns=X.columns)

# Make copy of the scaled features
df_preprocessed = X_scaled.copy()

# Add original target/y variable to scaled data frame
df_preprocessed['Target'] = y.values
'''
# Test
print(df_preprocessed.shape)
display(df_preprocessed.head())
display(df_preprocessed.describe().transpose())
'''

# Save processed dataset as new .csv file
df_preprocessed.to_csv('../student_data_processed_20251208.csv', index = False) # Drop column "Unnamed: 0" from table